site_name: Polytoria Scripting API
copyright: Copyright &copy; 2019 - 2021 Polytoria
theme:
  features:
    - navigation.tabs
    - navigation.instant
    - content.code.annotate
  name: material
  logo: assets/icon.png
  font:
    text: Poppins
  palette: 
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/weather-night
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - tables