name: Deploy
on:
  push:
    branches: main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - run: |
          set -euo pipefail
          pip install -r requirements.txt
          mkdocs build -s
          mkdir ~/.ssh
          echo '${{ secrets.KEY }}' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          rsync -aze 'ssh -o StrictHostKeyChecking=no' --delete --force site/ ${{ secrets.USER }}@${{ secrets.HOST }}:${{ secrets.DEST }}
