name: Prettier Format and Commit

on:
  push:
    branches:
      - main
      - refs/heads/*

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run Prettier
        run: pnpm run format

      - name: Commit changes
        id: commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff-index --quiet HEAD; then
            echo "No changes to commit."
            echo "changes_committed=false" >> $GITHUB_ENV
          else
            git commit -m "chore: format code with Prettier"
            echo "changes_committed=true" >> $GITHUB_ENV
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        if: env.changes_committed == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: format code with Prettier'
          branch: prettier-fix
          title: 'chore: format code with Prettier'
          body: This PR formats the code with Prettier.
          labels: prettier
